import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eyadaty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/logo.png" />
      </Head>

      <header className={styles.Header}>
        <div className={styles.ktop}>
          <div className={styles.filldiv}>
            <a href="#" className={styles.krozalissink}>
              Rozaliss
            </a>
            <div className={styles.topright}>
              <a href="#" className={styles.topcompte}>Compte Proféssionel ?</a>
              <a href="#" className={styles.topblog}>Blog</a>
              <div className={styles.topflag}>
              </div>
            </div>
          </div>
        </div>

        <div className={styles.kbottom}>
            <div className={styles.filldiv}>
              <Image src="/src/Logo.png" alt="Eyadaty Logo" width={56} height={56}></Image>
              <div className={styles.navigations}>
                <a href="#" className={styles.onenavigationvisited}>Accueil</a>
                <a href="#" className={styles.onenavigation}>À propos de nous</a>
                <a href="#" className={styles.onenavigation}>Contactez-nous</a>
              </div>
              <div className={styles.searchdiv}>
                <div className={styles.filldiv}>
                  <input className={styles.headersearch} placeholder="Chercher..." type="text"/>
                  <div className={styles.searchimage}>
                  <Image src="/src/Search.png" alt="Search" width={16} height={16}></Image>
                  </div>
                  
                </div>
              </div>
              <div className={styles.headerbuttons}>
                <div className={styles.filldiv}>
                  <button className={styles.buttonlogin}>Connexion</button>
                  <button className={styles.buttonregister}>S'inscrire</button>
                </div>
              </div>
            </div>
        </div>
      </header>
      
      <div className={styles.Hero}>
        <div className={styles.filldiv}>
          <div className={styles.content}>
            <p className={styles.Headline}>Retrouver la belle vie par une bonne santé.</p>
            <p className={styles.Text}>Nous éliminons les conjectures pour trouver les bons médecins, hôpitaux et soins pour vous et votre famille.</p>
          </div>
          <div className={styles.avatar}>
            <Image src="/src/avatar.png" alt="Avatar" width={548} height={528}></Image>
          </div>
        </div>
      </div>

      <div className={styles.searchform}>
        <div className={styles.filldiv}>
          <div className={styles.form}>

          </div>
          <div className={styles.link}>

          </div>
          <div className={styles.tags}>

          </div>
        </div>
      </div>
    </div>
  )
}
